### ISSUE TITLE
A user can view items for sale.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/Online-Store#1]
# Motivation:
User will be able to see all the products for sale on the webpage.

# Task
- [x] Set up html/css/js pages and link together
- [x] Add name/logo of online store at top/header
- [x] Add statement about products for sale under name
- [x] Create basic set-up/grid with containers of how products will be laid out in body and how many will be included on the page.
- [x] Add pictures of products
- [x] Add product title under product
- [x] Add basic contact info in footer

**Comment by stephyacek** [comment]
<img width="768" alt="screen shot 2017-06-13 at 8 51 52 pm" src="https://user-images.githubusercontent.com/29046195/27145278-00598d5e-50ea-11e7-8d42-4e98ab6a6328.png">
