### ISSUE TITLE
A user can view the details of an item.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/Online-Store#2]
# Motivation:
User will be able to see enlarged photo and read description of product.

# Tasks:
- [x] Create framework of how details page will look.
- [x] Add detail information to product array.
- [x] Create function to show art detail array in hidden div.
- [x] Add id to array items to know when item is clicked.
- [x] Add hidden class to art detail page.
- [x] Create button to bring back to all artwork showing.
- [x] Add click event to find what photo clicked on.
- [x] Toggle hidden/show depending on what was clicked.
- [x] Clicking 'back' button will bring back to original page.

**Comment by stephyacek** [comment]
<img width="816" alt="screen shot 2017-06-14 at 12 26 38 pm" src="https://user-images.githubusercontent.com/29046195/27150636-d504386c-50fc-11e7-94a3-5932fc504b41.png">

**Comment by stephyacek** [comment]
<img width="1342" alt="screen shot 2017-06-14 at 4 17 44 pm" src="https://user-images.githubusercontent.com/29046195/27158685-141fe2b0-511d-11e7-991a-892352f53584.png">
