### ISSUE TITLE
A user can add an item to their cart.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/Online-Store#3]
# Motivation:
Users will have the ability to decide to purchase prints by first adding them to their virtual shopping cart.

# Tasks:
- [x] Create layout of shopping cart components in html/css.
- [x] Create span under detailed text when detailed art page is displayed.
- [x] Create dropdown with size options.
- [x] Create input with quantity to purchase.
- [x] Create "Add to Cart" button
- [x] Size and quantity is saved into a cart array.

**Comment by stephyacek** [comment]
<img width="779" alt="screen shot 2017-06-16 at 3 02 49 pm" src="https://user-images.githubusercontent.com/29046195/27246343-c7d0d722-52a5-11e7-9c88-7910e4e1605b.png">
