### ISSUE TITLE
A user can view and manage the items in their cart.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/Online-Store#4]
# Motivation:
User will be able to edit what is in their cart.

# Tasks:
- [x] Create layout for 'My Cart' page
- [x] Create 'My Cart' page to be rendered when cart image clicked on.
- [x] Show 'Back to Gallery' button 
- [x] Disable going to cart without anything in cart.
- [x] Automatically increase the same product if same print/size added to cart again without new object array created.
- [x] List out items in cart on page.
- [x] Show calculation of total cost in cart before proceeding to checkout
- [x] Allow user to change quantity of product in cart
- [x] Allow user to delete items in cart.

**Comment by stephyacek** [comment]
<img width="850" alt="screen shot 2017-06-20 at 10 06 09 am" src="https://user-images.githubusercontent.com/29046195/27345902-2600a05a-55a0-11e7-8ec8-ca596dbe5ad9.png">

**Comment by stephyacek** [comment]
<img width="1432" alt="screen shot 2017-06-22 at 9 32 48 am" src="https://user-images.githubusercontent.com/29046195/27445222-cd3e4f50-572d-11e7-8122-ea9e1d44f26e.png">
