### ISSUE TITLE
A user can checkout.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/Online-Store#5]
# Motivation:
Users will be see their order total and check out.
 
# Task:
- [x] Create form framework
- [x] Add click listener to Checkout button to bring up Checkout page. 
- [x] Create different sections for billing, payment and shipping.
- [ ] Style sections
- [ ] Use form validation to ensure form is complete before submitting.
